Reorganization, prep for unit testing

diff --git a/jenny b/jenny
--- a/jenny
+++ b/jenny
@@ -1,27 +1,66 @@
 #!/usr/bin/env bash
 
-BLOGRC="$PWD/.blogrc"
+# Declare CONSTANTS
+PUBLISH_PATTERN="^[0-9]{4}-[0-9]{2}-[0-9]{2}(.*)"
+COMPILE_HISTORY_FILE=$(pwd)/.compile_history
+SOURCE_TEMP_FILE=/tmp/jennysource
+RENDER_TEMP_FILE=/tmp/jennyrender
+SHARE_DIR=/usr/local/share/jenny
+T="[jenny]"
+
+# Use project dir when symlinked
+if [[ "$(uname -a)" == *"Darwin"* ]]; then
+  SCRIPT_DIR=$(dirname "$(readlink $(which $BASH_SOURCE))")
+else
+  SCRIPT_DIR=$(dirname -- "$(readlink -e -- $BASH_SOURCE)")
+fi
+
+# Load library
+source $SCRIPT_DIR/lib/*.sh
 
 # Load configuration on current dir
-if [ -f "$BLOGRC" ]; then
-  source $BLOGRC
+if source_blogrc; then
+  echo "$T Sourced .blogrc"
+
+  # Set defaults if not set in .blogrc
+  [ -z $POSTS_PER_PAGE ] && POSTS_PER_PAGE=5
+  [ -z $DIST ] && DIST=$PWD/.dist
+
+  if is_installed; then
+    # Installed, use installation path
+    [ -z "$LAYOUT_DIR" ] && LAYOUT_DIR=$SHARE_DIR/layout
+    [ -z "$MARKDOWN_COMMAND" ] && MARKDOWN_COMMAND="\$AWK -f \$SHARE_DIR/lib/md2html.awk"
+  else
+    # Not installed, use project path
+    [ -z "$LAYOUT_DIR" ] && LAYOUT_DIR=$SCRIPT_DIR/share/layout
+    [ -z "$MARKDOWN_COMMAND" ] && MARKDOWN_COMMAND="\$AWK -f \$SCRIPT_DIR/share/lib/md2html.awk"
+  fi
+
+  # Sets up directory
+  touch $COMPILE_HISTORY_FILE
+  mkdir -p $DIST/post
+  mkdir -p $DIST/page
+
+  if [ "$STATIC_DIRS" ]; then
+    eval "cp -R $STATIC_DIRS $DIST"
+  fi
 else
-  echo "This is not a blog. Exiting.";
-  exit 0
+  echo "$T Could not find .blogrc in this directory, exiting."
+  exit 1
 fi
 
 # Checks if user is on macOS and checks for dependencies
 # Also handles suppresion of this very message
-if [ -z "$SUPPRESS_UTILS_WARN" ] && [[ "$(uname -a)" == *"Darwin"*  && ( -z "$(which gsed)" || -z "$(which gawk)" ) ]]; then
-  echo -e "macOS users need 'gsed', 'gawk', and  'gdate', install them via: brew install gawk gnu-sed coreutils\n"
+if is_utils_installed; then
+  echo -e "$T macOS users need gsed, gawk, and gdate, install them via: \n\n  brew install gawk gnu-sed coreutils\n"
   echo -e "If you installed them with --with-default-names, i.e. as sed and awk, then add the below to your .blogrc file to suppress this warning:\n\n  SUPPRESS_UTILS_WARN=1\n"
-  echo "Exiting."
   exit 0
 fi
 
-# Set posts_per_page if not set in .blogrc
-[ -z "$POSTS_PER_PAGE" ] && POSTS_PER_PAGE=5
-[ -z "$DIST" ] && DIST=$PWD/.dist
+# Use GNU utils if present
+[ "$(which gsed)" ] && SED=$(which gsed) || SED=$(which sed)
+[ "$(which gawk)" ] && AWK=$(which gawk) || AWK=$(which awk)
+[ "$(which gdate)" ] && DATE=$(which gdate) || DATE=$(which date)
 
 # Declare GlobalVariables
 FullFileName=""
@@ -37,54 +76,6 @@ PostCount=0
 PageCount=0
 declare -a IndexList
 
-# Declare CONSTANTS
-PUBLISH_PATTERN="^[0-9]{4}-[0-9]{2}-[0-9]{2}(.*)"
-COMPILE_HISTORY_FILE=$PWD/.compile_history
-SOURCE_TEMP_FILE=/tmp/jennysource
-RENDER_TEMP_FILE=/tmp/jennyrender
-SHARE_DIR=/usr/local/share/jenny
-
-# Prepares last modification/compiled database
-touch $COMPILE_HISTORY_FILE
-
-# Use project dir when symlinked
-if [[ "$(uname -a)" == *"Darwin"* ]]; then
-  SCRIPT_DIR=$(dirname "$(readlink $(which $BASH_SOURCE))")
-else
-  SCRIPT_DIR=$(dirname -- "$(readlink -e -- $BASH_SOURCE)")
-fi
-
-# h/t https://gist.github.com/TheMengzor/968e5ea87e99d9c41782
-# Populate flag to check if installed
-SOURCE="${BASH_SOURCE[0]}"
-while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
-  ABSOLUTE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
-  SOURCE="$(readlink "$SOURCE")"
-  [[ $SOURCE != /* ]] && SOURCE="$ABSOLUTE_DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
-done
-ABSOLUTE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
-
-if [ -z "$ABSOLUTE_DIR" ]; then
-  # Not installed, use project paths
-  [ -z "$LAYOUT_DIR" ] && LAYOUT_DIR=$SCRIPT_DIR/share/layout
-else
-  # Installed, use installation paths
-  [ -z "$LAYOUT_DIR" ] && LAYOUT_DIR=$SHARE_DIR/layout
-fi
-
-if [ -z "$MARKDOWN_COMMAND" ]; then
-  if [ -z "$ABSOLUTE_DIR" ]; then
-    MARKDOWN=$SCRIPT_DIR/share/lib/md2html.awk
-  else
-    MARKDOWN=$SHARE_DIR/lib/md2html.awk
-  fi
-  MARKDOWN_COMMAND="\$AWK -f \$MARKDOWN"
-fi
-
-if [ "$STATIC_DIRS" ]; then
-  eval "cp -R $STATIC_DIRS $DIST"
-fi
-
 while getopts ":d:p:l:" opt; do
   case $opt in
     d) DIST="$OPTARG"
@@ -97,29 +88,6 @@ while getopts ":d:p:l:" opt; do
     ;;
   esac
 done
-
-# Create directories for pseudo subdirs
-mkdir -p $DIST/post
-mkdir -p $DIST/page
-
-# Use GNU utils if present
-[ "$(which gsed)" ] && SED=$(which gsed) || SED=$(which sed)
-[ "$(which gawk)" ] && AWK=$(which gawk) || AWK=$(which awk)
-[ "$(which gdate)" ] && DATE=$(which gdate) || DATE=$(which date)
-
-# Fn Helpers
-ceiling_divide() {
-  ceiling_result=$((($1+$2-1)/$2))
-}
-
-clean() {
-  rm -f $_DIST/index.html
-  rm -rf $_DIST/page/
-  rm -rf $_DIST/tag/
-  rm -rf /tmp/jenny*
-}
-
-function join_by { local IFS="$1"; shift; echo "$*"; }
 
 # Used to generate info from filename
 parse_details () {
